binop_separator = "Back"
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
combine_control_expr = false
comment_width = 80
edition = "2018"
empty_item_single_line = true
fn_params_layout = "Vertical"
hard_tabs = false
hex_literal_case = "Lower"
max_width = 80
imports_granularity = "Item"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
wrap_comments = true
use_try_shorthand = true
#where_single_line = true
trailing_comma = "Never"
